---
title: "Untitled"
author: "Michael Sieler"
date: "2022-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Development 2.0

Checking to see if adding pre-exposed fish that aren't `Treatment == 'control'` makes a difference to the analysis

```{r}

data <- df.conT0T1_2
data.alpha <- dt.alphaPlus.conT0T1_2.melt
ps.obj <- ps.conT0T1_2
dist <- distList.conT0T1_2

levels(data.alpha$Timepoint) <- factor(levels(data.alpha$Timepoint), levels = c("3mpf", "6mpf"))
data.alpha$Timepoint <- relevel(factor(data.alpha$Timepoint), ref = "3mpf")

```

### Alpha Diversity

#### Time

```{r Dev-Alpha-Time}


tukey.test.list <- lapply(methods.alpha, function(alpha){
  summary(multcomp::glht(glm(formula = Alpha.Score ~ -1 + Timepoint, 
                             data = data.alpha %>% filter(Alpha.Metric == alpha),
                             family = "quasibinomial"), 
                             linfct = mcp(Timepoint = "Tukey")) ) %>% 
  tidy() %>%
  separate(contrast, c('group1', 'group2'), sep = " - ") %>%
  select(-c(null.value)) %>%
  rename(p.adj = adj.p.value) %>%
  mutate(p.adj.signif = case_when(p.adj < 0.05 ~ "*",
                                  p.adj >= 0.05 ~ "ns")) %>%
  mutate(`.y.` = "Alpha.Score", .after = 1) %>%
  mutate(metric = alpha, .before = 1)
})

plot.sig.labs <- lapply(methods.alpha, function(alpha){ 
  tukey.test.list[[alpha]] %>% 
  as_tibble() %>% 
  select(`.y.`, group1, group2, p.adj.signif)
})


Fig.2.a <-
  data.alpha %>%
  filter(Alpha.Metric == "Shannon") %>%
    ggplot(aes(x = Timepoint, 
               y = Alpha.Score
               )) +
    geom_boxplot(aes(fill = Timepoint)) +
    geom_quasirandom(size = 1) +
    # facet_grid(. ~ Diet, scale = "free") +
    scale_fill_manual(values = pal.Dark2[c(6,4)]) +
    scale_color_manual(values = pal.Dark2[c(6,4)]) +
    labs(
      # title = "",
      # caption = "",
      x = "Time",
      y = "Alpha Score (normalized)"
    ) +
    ggpubr::stat_pvalue_manual(plot.sig.labs[["Shannon"]], 
                               label = "p.adj.signif", 
                               size = 6,
                               bracket.size = 1,
                               y.position = c(1.075)
                               ) +
    scale_y_continuous(breaks = scales::breaks_pretty(n = 5),
                       limits = c(0, 1.1)) +
  theme(legend.position = "none")

Fig.2.a


# Stats

# Build GLM Model
mod.list <- lapply(methods.alpha, function(alpha){
  glm( formula = "Alpha.Score ~ Timepoint",
       data = subset(data.alpha, Alpha.Metric == alpha),
       family = "quasibinomial")
}) %>% setNames(methods.alpha)

# Model Output
lapply(methods.alpha, function(x){
  mod.list[[x]] %>% 
    tidy() %>%
    mutate(metric = x, .before = 1) %>%
      mutate(sig = ifelse(p.value <= 0.05, "*", ""))
}) %>% bind_rows() %>%
  flextable() %>%
  colformat_double(j = 3:5, digits = 3) %>%
  merge_v(j = 1)  %>%
  set_formatter(values = list("p.value" = p_val_format) ) %>%
  hline(i = c(2,4), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("glm(Alpha.Score ~ Time), family = quasibinomial)"))

# Anova
lapply(methods.alpha, function(x){
  mod.list[[x]] %>% Anova(type = 2) %>%
    tidy() %>%
    mutate(metric = x, .before = 1)  %>%
      mutate(sig = ifelse(p.value <= 0.05, "*", ""))
}) %>% bind_rows() %>%
    flextable() %>%
    # align(j = 3:6, align = "right") %>%
    colformat_double(j = 3, digits = 3) %>%
    merge_v(j = 1) %>%
    set_formatter(values = list("p.value" = p_val_format) ) %>%
    set_caption(paste0("ANOVA( glm(Alpha.Score ~ Time), family = quasibinomial) )")) %>%
    autofit()

# Tukey's Pairwise Comparison
tukey.test.list %>%
  bind_rows() %>%
  flextable() %>%
  align(j = 3:6, align = "right") %>%
  colformat_double(j = 6:9, digits = 3) %>%
  merge_v(j = 1) %>%
  set_formatter(values = list("adj.p.value" = p_val_format) ) %>%
  # hline(i = c(3,6), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("Pairwise Tukey's HSD, p.adj: Dunnett. glm(Alpha.Score ~ Timepoint), family = quasibinomial)")) %>%
  autofit()

```

#### Time:Diets


```{r Dev-Alpha-TimeDiets}

tukey.test.list <- lapply(methods.alpha, function(alpha){
  test <- data.alpha %>%
    filter(Alpha.Metric == alpha) %>%
    group_by(Diet) %>%
    nest(data = -Diet) %>%
    mutate(test = map(.x=data, 
                      ~summary(multcomp::glht(glm(formula = Alpha.Score ~ -1 + Timepoint, 
                           data = .x,
                           family = "quasibinomial"), 
                           linfct = mcp(Timepoint = "Tukey")) )%>% tidy
                      )) %>%
    unnest(test) %>%
    separate(contrast, c('group1', 'group2'), sep = " - ") %>%
    select(-c(data, null.value)) %>%
    rename(p.adj = adj.p.value) %>%
    mutate(p.adj.signif = case_when(p.adj < 0.05 ~ "*",
                                    p.adj >= 0.05 ~ "ns")) %>%
    mutate(`.y.` = "Alpha.Score", .after = 1) %>%
    arrange(Diet)%>%
  mutate(metric = alpha, .before = 1)
})



plot.sig.labs <- lapply(methods.alpha, function(alpha){ 
  tukey.test.list[[alpha]] %>% 
  as_tibble() %>% 
  select(Diet, `.y.`, group1, group2, p.adj.signif)
})


Fig.2.b <- lapply(methods.alpha, function(alpha){ 
  data.alpha %>%
  filter(Alpha.Metric == alpha) %>%
    ggplot(aes(x = Timepoint, 
               y = Alpha.Score
               )) +
    geom_boxplot(aes(fill = Timepoint)) +
    geom_quasirandom(size = 1) +
    facet_grid(. ~ Diet, scale = "free") +
    scale_fill_manual(values = pal.Dark2[c(6,4)]) +
    scale_color_manual(values = pal.Set1) +
    labs(
      # title = "",
      caption = alpha,
      x = "Time",
      y = "Alpha Score (normalized)"
    ) +
    ggpubr::stat_pvalue_manual(plot.sig.labs[["Observed"]], 
                               label = "p.adj.signif", 
                               size = 6,
                               bracket.size = 1,
                               y.position = c(.95, .95, 1.075)
                               ) +
    scale_y_continuous(breaks = scales::breaks_pretty(n = 5),
                       limits = c(0, 1.1)) +
  theme(legend.position = "none")

})
  
Fig.2.b

# Stats

# Build GLM Model
mod.list <- lapply(methods.alpha, function(alpha){
  glm( formula = "Alpha.Score ~ Diet*Timepoint",
       data = subset(data.alpha, Alpha.Metric == alpha),
       family = "quasibinomial")
}) %>% setNames(methods.alpha)

# Model Output
lapply(methods.alpha, function(x){
  mod.list[[x]] %>% 
    tidy() %>%
    mutate(metric = x, .before = 1) %>%
      mutate(sig = ifelse(p.value <= 0.05, "*", ""))
}) %>% bind_rows() %>%
  flextable() %>%
  colformat_double(j = 3:5, digits = 3) %>%
  merge_v(j = 1)  %>%
  set_formatter(values = list("p.value" = p_val_format) ) %>%
  hline(i = c(6, 12), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("glm(Alpha.Score ~ Diet*Time), family = quasibinomial)"))

# Anova
lapply(methods.alpha, function(x){
  mod.list[[x]] %>% Anova(type = 2) %>%
    tidy() %>%
    mutate(metric = x, .before = 1)  %>%
      mutate(sig = ifelse(p.value <= 0.05, "*", ""))
}) %>% bind_rows() %>%
    flextable() %>%
    # align(j = 3:6, align = "right") %>%
    colformat_double(j = 3, digits = 3) %>%
    merge_v(j = 1) %>%
    hline(i = c(3,6), j = NULL, border = NULL, part = "body") %>%
    set_formatter(values = list("p.value" = p_val_format) ) %>%
    set_caption(paste0("ANOVA( glm(Alpha.Score ~ Diet*Time), family = quasibinomial) )")) %>%
    autofit()

# Tukey's Pairwise Comparison
tukey.test.list %>%
  bind_rows() %>%
  flextable() %>%
  align(j = 3:6, align = "right") %>%
  colformat_double(j = 6:9, digits = 3) %>%
  merge_v(j = 1) %>%
  set_formatter(values = list("adj.p.value" = p_val_format) ) %>%
  hline(i = c(3,6), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("Pairwise Tukey's HSD, p.adj: Dunnett. glm(Alpha.Score ~ Timepoint), family = quasibinomial)")) %>%
  autofit()


```

### Beta Diversity

#### Diets

```{r Dev-Beta-Diets}

# Full dbRDA models
mod <- full_dbrda_model(vars = c("Diet"),  # Enter variables as a list "c(var.A, var.B, var.C)"
                          distance = dist,
                          methods = methods.beta,
                          names = set_names_beta,
                          physeq = ps.obj,
                          data = data,
                          terms = 1,  # if you want interaction terms enter 2, otherwise 1
                          num.cores = num.cores
                        )

anova <- beta_anova(beta.model = mod,
                    methods = methods.beta,
                    names = set_names_beta,
                    num.cores = num.cores)


# Plot prep
dt.ord.full.beta <- ord_dt_list(mod, ps.obj)
beta.dt.full <- samp_coord_dt(dt.ord.full.beta, methods.beta)
beta.axis.full <- axis_labels(dt.ord.full.beta)

Fig.2.c <- lapply(methods.beta, function(beta){

p.val <- anova$p.value[anova$metric == beta][1]
p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords[[3]])
cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords[[2]])


  dt.ord.full.beta[[beta]]$sample.coords %>%
    ggplot(aes(x = .[[2]], y = .[[3]])) +
      stat_ellipse(aes(color = Diet )) +
      geom_point(aes(color = Diet),
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(values = col.Diet) +
      scale_color_manual(values = col.Diet)  + 
      labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")
})

Fig.2.c

Fig.2.c.2 <- lapply(methods.beta, function(beta){

p.val <- anova$p.value[anova$metric == beta][1]
p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords[[3]])
cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords[[2]])


  dt.ord.full.beta[[beta]]$sample.coords %>%
    ggplot(aes(x = .[[2]], y = .[[3]])) +
      stat_ellipse(aes(color = Timepoint )) +
      geom_point(aes(color = Timepoint),
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(values = col.Time) +
      scale_color_manual(values = col.Time)  + 
      labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")
})

Fig.2.c.2

Fig.2.c.3 <- lapply(methods.beta, function(beta){

p.val <- anova$p.value[anova$metric == beta][1]
p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords[[3]])
cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords[[2]])


  dt.ord.full.beta[[beta]]$sample.coords %>%
    ggplot(aes(x = .[[2]], y = .[[3]])) +
      stat_ellipse(aes(color = Diet )) +
      geom_point(aes(color = Diet, fill = Timepoint),
                 shape = 21,
                 size = 2.5,
                 stroke = 1.25,
                 alpha = 1) +
      annotate("text", 
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(name = "Time", values = col.Time) +
      scale_color_manual(name = "Diet",values = col.Diet)  + 
      labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")
})

Fig.2.c.3

stats_table(anova) %>%
  set_caption(paste0("Distance-based redundancy analysis (dbRDA) ordination. Beta.Score ~ Diet"))


```



#### Time

```{r Dev-Beta-Time}


# Full dbRDA models
mod <- full_dbrda_model(vars = c("Timepoint"),  # Enter variables as a list "c(var.A, var.B, var.C)"
                          distance = dist,
                          methods = methods.beta,
                          names = set_names_beta,
                          physeq = ps.obj,
                          data = data,
                          terms = 1,  # if you want interaction terms enter 2, otherwise 1
                          num.cores = num.cores
                        )

anova <- beta_anova(beta.model = mod,
                    methods = methods.beta,
                    names = set_names_beta,
                    num.cores = num.cores)


# Plot prep
dt.ord.full.beta <- ord_dt_list(mod, ps.obj)
beta.dt.full <- samp_coord_dt(dt.ord.full.beta, methods.beta)
beta.axis.full <- axis_labels(dt.ord.full.beta)

Fig.2.d <-lapply(methods.beta, function(beta){

  p.val <- anova$p.value[anova$metric == beta][1]
  p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
  cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords[[3]])
  cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords[[2]])

  dt.ord.full.beta[[beta]]$sample.coords %>%
    ggplot(aes(x = CAP1, y = MDS1)) +
      stat_ellipse(aes(color = Timepoint )) +
      geom_point(aes(color = Timepoint),
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(name = "Time", values = pal.Dark2[c(6,4)]) +
      scale_color_manual(name = "Time", values = pal.Dark2[c(6,4)])  + 
      labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")
})

Fig.2.d

Fig.2.d.2 <-lapply(methods.beta, function(beta){

  p.val <- anova$p.value[anova$metric == beta][1]
  p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
  cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords[[3]])
  cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords[[2]])

  dt.ord.full.beta[[beta]]$sample.coords %>%
    ggplot(aes(x = CAP1, y = MDS1)) +
      stat_ellipse(aes(color = Diet )) +
      geom_point(aes(color = Diet),
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(name = "Time", values = col.Diet) +
      scale_color_manual(name = "Time", values = col.Diet)  + 
      labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")
})

Fig.2.d.2



stats_table(anova) %>%
  set_caption(paste0("Distance-based redundancy analysis (dbRDA) ordination. Beta.Score ~ Time"))

```


#### (SM) Diets:Time


```{r}

# Full dbRDA models
mod <- full_dbrda_model(vars = c("Timepoint", "Diet"),  # Enter variables as a list "c(var.A, var.B, var.C)"
                          distance = dist,
                          methods = methods.beta,
                          names = set_names_beta,
                          physeq = ps.obj,
                          data = data,
                          terms = 2,  # if you want interaction terms enter 2, otherwise 1
                          num.cores = num.cores
                        )

anova <- beta_anova(beta.model = mod,
                    methods = methods.beta,
                    names = set_names_beta,
                    num.cores = num.cores)


# Plot prep
beta.metric <- 'Bray-Curtis'
dt.ord.full.beta <- ord_dt_list(mod, ps.obj)
beta.dt.full <- samp_coord_dt(dt.ord.full.beta, methods.beta)
beta.axis.full <- axis_labels(dt.ord.full.beta)





Fig.2.x.1 <- lapply(methods.beta, function(beta){
  
  p.val <- anova$p.value[anova$metric == beta][1]
  p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
  cap.min <- min(dt.ord.full.beta[[beta.metric]]$sample.coords[[3]])
  cap.max <- max(dt.ord.full.beta[[beta.metric]]$sample.coords[[2]])


  dt.ord.full.beta[[beta.metric]]$sample.coords %>%
    ggplot(aes(x = CAP1, y = CAP2)) +
      stat_ellipse(aes(color = Diet, linetype = Timepoint )) +
      geom_point(aes(color = Diet,
                     shape = Timepoint),
                 # shape = 21,
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               # label = paste0(beta.metric, "; ", p.val.label),
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(name = "Diet", values = pal.Dark2) +
      scale_color_manual(name = "Diet", values = pal.Dark2)  + 
      scale_shape_manual(name = "Time", values = c(19, 1)) +
      labs(x = dt.ord.full.beta[[beta.metric]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta.metric]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")

})
  
Fig.2.x.1

Fig.2.x.2 <- lapply(methods.beta, function(beta){
  
  p.val <- anova$p.value[anova$metric == beta.metric][1]
  p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
  cap.min <- min(dt.ord.full.beta[[beta.metric]]$sample.coords[[3]])
  cap.max <- max(dt.ord.full.beta[[beta.metric]]$sample.coords[[2]])


  dt.ord.full.beta[[beta.metric]]$sample.coords %>%
    ggplot(aes(x = CAP1, y = CAP2)) +
      stat_ellipse(aes(color = Timepoint, linetype = Diet )) +
      geom_point(aes(color = Timepoint,
                     fill = Timepoint,
                     shape = Diet
                     ),
                 # shape = 21,
                 size = 2.5,
                 alpha = 1) +
      annotate("text", 
               # label = paste0(beta.metric, "; ", p.val.label),
               label = p.val.label,
               x = cap.max, y = cap.min, 
               size = 5, 
               color = "black",
               hjust = .95
      ) +
      scale_fill_manual(name = "Diet", values = col.Time) +
      scale_color_manual(name = "Diet", values = col.Time)  + 
      # scale_shape_manual(name = "Time", values = c(19, 1)) +
      labs(x = dt.ord.full.beta[[beta.metric]]$axes.labs[1], 
           y = dt.ord.full.beta[[beta.metric]]$axes.labs[2],
           caption = beta) + 
      theme(legend.position = "bottom")

})
  
Fig.2.x.2


stats_table(anova) %>%
  set_caption(paste0("Distance-based redundancy analysis (dbRDA) ordination. Beta.Score ~ Diet*Time"))

```




```{r Dev-Beta-Diets}

# Full dbRDA models
mod <- full_dbrda_model(vars = c("Diet", "Timepoint"),  # Enter variables as a list "c(var.A, var.B, var.C)"
                          distance = dist,
                          methods = methods.beta,
                          names = set_names_beta,
                          physeq = ps.obj,
                          data = data,
                          terms = 2,  # if you want interaction terms enter 2, otherwise 1
                          num.cores = num.cores
                        )

anova <- beta_anova(beta.model = mod,
                    methods = methods.beta,
                    names = set_names_beta,
                    num.cores = num.cores)


stats_table(anova) %>%
  set_caption(paste0("Distance-based redundancy analysis (dbRDA) ordination. Beta.Score ~ Diet:Time"))

```

#### (SM) Beta-Dispersion

```{r}
data.beta <- lapply(ord.beta, function(beta){
  
  tmp.ord <- ordinate(
      physeq = ps.obj, 
      method = "PCoA",  # c("DCA", "CCA", "RDA", "CAP", "DPCoA", "NMDS", "MDS", "PCoA")
      distance = beta  # c("bray", "canberra", "sor")
    )
  
  tmp.ord.data <- list()
  tmp.ord.data[[beta]] <- plot_ordination(
      physeq = ps.obj,
      ordination = tmp.ord,
      justDF = T
    )
  
}) %>% set_names(ord.beta)
```


##### Diet

```{r}

# Beta-dispersion Table
ord.beta <- c("bray", "canberra")
beta.disp <- list()
beta.disp <- lapply(dist[1:2], function(beta) {
  set.seed(42)
  betadisper(beta, group = data$Diet)  %>% permutest(pairwise = T, permutations = 999)
  
}) %>% setNames(ord.beta)

lapply(dist[1:2], function(beta) {
  set.seed(42)
  betadisper(beta, group = data$Diet)  %>% boxplot()
  
}) 

# Anova
lapply(beta.disp, function(beta) {
  beta$tab %>% 
    flextable()
})

# Permutation table
lapply(beta.disp, function(beta) {
  # print(beta)
  beta$pairwise$permuted %>%
    tidy() %>%
    rename(Names = names,
           `p-value` = x) %>%
    flextable()
})
```


##### Time

```{r}

# Beta-dispersion Table
ord.beta <- c("bray", "canberra")
beta.disp <- list()
beta.disp <- lapply(dist[1:2], function(beta) {
  betadisper(beta, group = data$Timepoint)  %>% permutest(pairwise = T, permutations = 999)
  
}) %>% setNames(ord.beta)

lapply(dist[1:2], function(beta) {
  betadisper(beta, group = data$Timepoint)  %>% boxplot(xlab = "Time")
  
}) 

# Anova
lapply(beta.disp, function(beta) {
  beta$tab %>% 
    flextable()
})

# Permutation table
lapply(beta.disp, function(beta) {
  # print(beta)
  beta$pairwise$permuted %>%
    tidy() %>%
    rename(Names = names,
           `p-value` = x) %>%
    flextable()
})
```

##### Diet:Time

```{r}

# Add interaction
data <- data %>%
  mutate(Diet.Time = paste0(Diet,".", Timepoint), .after = Age)

# Beta-dispersion Table
ord.beta <- c("bray", "canberra")
beta.disp <- list()
beta.disp <- lapply(dist[1:2], function(beta) {
  betadisper(beta, group = data$Diet.Time)  %>% permutest(pairwise = T, permutations = 999)
  
}) %>% setNames(ord.beta)

lapply(dist[1:2], function(beta) {
  betadisper(beta, group = data$Diet.Time)  %>% boxplot(col = col.Diet[c(1,1,2,2,3,3)],
                                                        xlab = "Diet & Time")
  
}) 

# Anova
lapply(beta.disp, function(beta) {
  beta$tab %>% 
    flextable()
})

# Permutation table
lapply(beta.disp, function(beta) {
  # print(beta)
  beta$pairwise$permuted %>%
    tidy() %>%
    rename(Names = names,
           `p-value` = x) %>%
    arrange(`p-value`) %>%
    flextable()
})
```


### Physiology

#### Body Condition Score

```{r Dev-Physio-BCS}

test <- data %>%
  # filter(Alpha.Metric == "Shannon") %>%
  group_by(Diet) %>%
  rstatix::wilcox_test(data =., Body.Condition.Score ~ Timepoint) %>%
  rstatix::adjust_pvalue(method = "BH") %>%
  rstatix::add_significance("p.adj")


Fig.2.e <-
  data %>%
  # filter(Alpha.Metric == "Shannon") %>%
    ggplot(aes(x = Timepoint, 
               y = Body.Condition.Score
               )) +
    geom_boxplot(aes(fill = Timepoint)) +
    geom_quasirandom(size = 1) +
    facet_grid(. ~ Diet, scale = "free") +
    scale_fill_manual(values = pal.Dark2[c(6,4)]) +
    scale_color_manual(values = pal.Set1) + 
    labs(
      # title = "",
      # caption = "",
      x = "Time",
      y = "Body Condition Score"
    ) +
    ggpubr::stat_pvalue_manual(test, 
                               label = "p.adj.signif", 
                               size = 6,
                               bracket.size = 1,
                               y.position = c(2.65, 2.75, 3.55)
                               ) +
    scale_y_continuous(breaks = scales::breaks_pretty(n = 5), 
                       limits = c(0, 3.75)) + 
  theme(legend.position = "none")

Fig.2.e

test %>% 
  flextable() %>%
  align(j = 3:6, align = "right") %>%
  colformat_double(j = 6:7, digits = 3) %>%
  merge_v(j = 1) %>%
  set_formatter(values = list("p" = p_val_format,
                              "p.adj" = p_val_format) ) %>%
  set_caption(paste0("Wilcoxon Test. p. adj: BH. Body.Condition.Score ~ Diet:Time")) %>%
  autofit()

```


#### ZIRC BCS ~ Alpha Diversity

```{r}

test.list <- lapply(methods.alpha, function(alpha){
    glm(formula = Alpha.Score ~ Body.Condition.Score, 
               data = data.alpha %>% filter(Alpha.Metric == alpha & Diet == "ZIRC"),
               family = "quasibinomial") %>% 
  Anova(type = 2) %>%
  tidy() %>% 
  mutate(term = c("Body Condition Score (ZIRC)"), 
         `.y.` = c("Alpha.Score"), 
         .before = 1) %>%
  mutate(metric = alpha, .before = 1)
})

# test <- data.alpha %>%
#   filter(Alpha.Metric == "Shannon" & Diet == "ZIRC") %>%
#   # group_by(Diet) %>%
#   rstatix::anova_test(data =., Body.Condition.Score ~ Alpha.Score) %>%
#   rstatix::adjust_pvalue(method = "BH") %>%
#   rstatix::add_significance("p.adj")

plot.label <- lapply(methods.alpha, function(alpha){ 
  paste0("F = ", round(test.list[[alpha]]$statistic, 3), "; P = ", round(test.list[[alpha]]$p.value, 3))
})

Fig.2.f <-
  data.alpha %>%
  filter(Alpha.Metric == "Shannon" & Diet == "ZIRC") %>%
    ggplot(aes(y = Alpha.Score, 
               x = Body.Condition.Score)
           ) +
    geom_smooth(aes(color = Diet, 
                    fill = Diet), 
                method = "lm") +
    geom_point(size = 2.5) +
    # facet_grid(. ~ Diet, scale = "free") +
    annotate("text", 
               label = plot.label[["Shannon"]],
               x = 3.5, y = 0.05, 
               size = 5, 
               color = "black",
               hjust = 1
      ) +
    scale_fill_manual(values = pal.Dark2[3]) +
    scale_color_manual(values = pal.Dark2[3]) + 
    labs(
      # title = "",
      # caption = "",
      y = "Alpha Score (normalized)",
      x = "Body Condition Score"
    ) +
    theme(legend.position = "none")

Fig.2.f


test.list %>%
  bind_rows() %>%
  flextable() %>%
  # align(j = 3:6, align = "right") %>%
  colformat_double(j = 4, digits = 3) %>%
  merge_v(j = 1) %>%
  set_formatter(values = list("p.value" = p_val_format) ) %>%
  # hline(i = c(3,6), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("glm(Alpha.Score ~ Body.Condition.Score), family = quasibinomial)")) %>%
  autofit()

```

#### (SM) ZIRC BetaDiv ~ BCS


```{r Dev-Beta-BCS}

# Full dbRDA models
mod <- full_dbrda_model(vars = c("Body.Condition.Score","Diet"),  # Enter variables as a list "c(var.A, var.B, var.C)"
                          distance = dist,
                          methods = methods.beta,
                          names = set_names_beta,
                          physeq = ps.obj,
                          data = data,
                          terms = 2,  # if you want interaction terms enter 2, otherwise 1
                          num.cores = num.cores
                        )

anova <- beta_anova(beta.model = mod,
                    methods = methods.beta,
                    names = set_names_beta,
                    num.cores = num.cores)


# # Plot prep
# dt.ord.full.beta <- ord_dt_list(mod, ps.obj)
# beta.dt.full <- samp_coord_dt(dt.ord.full.beta, methods.beta)
# beta.axis.full <- axis_labels(dt.ord.full.beta)
# p.val <- anova$p.value[anova$metric == "Bray-Curtis"][1]
# p.val.label <- paste0("p-value", ifelse(p.val == 0.001, " < ", " = " ), p.val)
# cap.min <- min(dt.ord.full.beta[[beta]]$sample.coords$CAP2)
# cap.max <- max(dt.ord.full.beta[[beta]]$sample.coords$CAP2)
# 
# 
# 
# Fig.2.c <-
#   dt.ord.full.beta[[beta]]$sample.coords %>%
#     ggplot(aes(x = CAP1, y = CAP2)) +
#       stat_ellipse(aes(color = Diet )) +
#       geom_point(aes(color = Diet),
#                  size = 2.5,
#                  alpha = 1) +
#       # geom_segment(
#       #     data = dt.ord.full.beta[[beta]]$vector.coords, 
#       #     aes(x = 0, y = 0, xend = CAP1, yend = CAP2),
#       #     color = "black",
#       #     arrow = arrow(length = unit(0.05, "npc"))
#       # ) +
#       annotate("text", 
#                label = p.val.label,
#                x = cap.max, y = cap.min, 
#                size = 5, 
#                color = "black",
#                hjust = .95
#       ) +
#       scale_fill_manual(values = pal.Dark2) +
#       scale_color_manual(values = pal.Dark2)  + 
#       labs(x = dt.ord.full.beta[[beta]]$axes.labs[1], 
#            y = dt.ord.full.beta[[beta]]$axes.labs[2]) + 
#       theme(legend.position = "bottom")
# 
# 
# Fig.2.c

stats_table(anova) %>%
  set_caption(paste0("Distance-based redundancy analysis (dbRDA) ordination. Beta.Score ~ Body.Condition.Score*Diet in ZIRC fed fish"))


```


### Differential Abundance

```{r}
res_global.TIME %>%
  tibble::rownames_to_column("Taxon") %>%
  filter(diff_abn == TRUE) %>%
  flextable() %>%
  align(j = 1:5, align = "right") %>%
  colformat_double(j = 2, digits = 3) %>%
  colformat_double(j = 3:4, digits = 4) %>%
  set_formatter(values = list("p_val" = p_val_format,
                              "q_val" = p_val_format) )
```


#### (SM) Diff Abundance

```{r}

df_fig_time = df_lfc.time %>% 
  dplyr::left_join(df_se.diets, by = c("Taxon_id", "Diet"), suffix = c("", ".SE")) %>%
  filter(if_any(contains("value"), ~ . != 0)) %>%
  dplyr::arrange(desc(value)) %>%
  dplyr::mutate(direct = ifelse(value > 0, "Positive LFC", "Negative LFC"))
# df_fig_diets$Taxon_id = df_fig_diets %>%
#   group_by(Taxon_id, Diet) %>% 
#   factor(levels = df_fig_diets$Taxon_id)
df_fig_diets$direct = factor(df_fig_diets$direct, 
                        levels = c("Positive LFC", "Negative LFC"))
  
plot =
ggplot(data = df_fig_time, 
           aes(x = reorder(Taxon_id, -value, FUN = mean), y = value, fill = Diet, color = Diet), group = Diet) + 
  geom_bar(stat = "identity", 
           position = position_dodge2(width = 1, preserve = "single"), width = .4) +
  geom_errorbar(aes(ymin = value - value.SE, ymax = value + value.SE), width = 0.4,
                position = position_dodge2(width = 1, preserve = "single"), color = "black") +
  labs(x = NULL, y = "Log fold change",
       title = paste0("Waterfall Plot of Diet:Time (", tax.label, ")")) +
  scale_fill_manual(values = pal.Dark2) +
  scale_color_manual(values = pal.Dark2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )

plot

```

