---
title: "ANCOM-BC"
author: "Michael Sieler"
date: "2022-08-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = NA, 
                      fig.width = 6.25, fig.height = 5)



# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("ANCOMBC")


# library(ANCOMBC)
# library(tidyverse)
library(microbiome)
# library(magrittr)
# library(qwraps2)
# library(corrplot)
# library(limma)
# library(ggforce)
# library(DT)


# Tutorial
#  https://bioconductor.org/packages/devel/bioc/vignettes/ANCOMBC/inst/doc/ANCOMBC.html

```


## Diet (6mo, controls)

### Load Data

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq = ps.T1 #%>% subset_samples(Diet == "Gemma")
data = dt.T1 #%>% subset(Diet == "Gemma")


```


### Run AncomBC

```{r}

set.seed(42)
output = ancombc2(data = pseq, tax_level = "Genus",
                  fix_formula = "Diet",
                  p_adj_method = "BH", pseudo = 0, pseudo_sens = TRUE,
                  prv_cut = 0.10, lib_cut = 1000, s0_perc = 0.05,
                  group = "Diet", #struc_zero = TRUE, neg_lb = TRUE,
                  alpha = 0.05, n_cl = 8, verbose = TRUE,
                  global = TRUE, pairwise = TRUE, dunnet = F, trend = F,
                  iter_control = list(tol = 1e-2, max_iter = 20, 
                                      verbose = TRUE),
                  em_control = list(tol = 1e-5, max_iter = 100),
                  # lme_control = lme4::lmerControl(),
                  mdfdr_control = list(fwer_ctrl_method = "BH", B = 100),
                  )

res_prim = output$res
res_global = output$res_global
res_pair = output$res_pair

```


### Summary Tables

```{r}

# Sensitivity Scores

tab_sens = output$pseudo_sens_tab
tab_sen <- tab_sens %>%
    flextable() %>%
  align(align = "right") %>%
  colformat_double(digits = 6) %>%
  # merge_v(j = 1) %>%
  set_formatter(values = list("adj.p.value" = p_val_format) ) %>%
  # hline(i = c(3,6), j = NULL, border = NULL, part = "body") %>%
  set_caption(paste0("ANCOM-BC2: Sensitivity Scores")) %>%
  autofit()



```


### Pairwise Analysis

```{r}

df_pair = res_pair %>%
    rownames_to_column("tax_id") 

df_fig_pair = df_pair %>%
    filter(diff_DietWatts == 1 | diff_DietZIRC == 1 |
               diff_DietZIRC_DietWatts == 1) %>%
    mutate(lfc_Watts = ifelse(diff_DietWatts == 1, 
                             lfc_DietWatts, 0),
           lfc_ZIRC = ifelse(diff_DietZIRC == 1, 
                                   lfc_DietZIRC, 0),
           lfc_Watts_ZIRC = ifelse(diff_DietZIRC_DietWatts == 1, 
                                        diff_DietZIRC_DietWatts, 0)) %>%
    transmute(tax_id, 
              `Gemma vs. Watts` = round(lfc_Watts, 2), 
              `Gemma vs. ZIRC` = round(lfc_ZIRC, 2),
              `Watts vs. ZIRC` = round(lfc_Watts_ZIRC, 2)
              ) %>%
    pivot_longer(cols = `Gemma vs. Watts`:`Watts vs. ZIRC`, 
                 names_to = "group", values_to = "value") %>%
    arrange(tax_id)
df_fig_pair$group = factor(df_fig_pair$group, 
                           levels = c("Gemma vs. Watts",
                                      "Gemma vs. ZIRC",
                                      "Watts vs. ZIRC"))
  
lo = floor(min(df_fig_pair$value))
up = ceiling(max(df_fig_pair$value))
mid = 0
fig_pair = df_fig_pair %>%
  ggplot(aes(x = group, y = tax_id, fill = value)) + 
  geom_tile(color = "black") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       na.value = "white", midpoint = mid, limit = c(lo, up),
                       name = NULL) +
  geom_text(aes(group, tax_id, label = value), color = "black", size = 4) +
  labs(x = NULL, y = NULL, title = "Log fold change of pairwise comparisons") +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

fig_pair

```

### Sensitivity analysis for diet

```{r}
sens_pair = tab_sens %>%
    rename_with(~gsub("(Intercept)", "DietGemma", .x, fixed = T)) %>%
      # Source: https://community.rstudio.com/t/replace-parts-of-a-column-name/116646/2
    transmute(sens_pair = `Gemma - Watts`) %>%
    rownames_to_column("tax_id") %>%
    left_join(df_pair %>%
                  transmute(tax_id, 
                            diff_pair = diff_DietWatts), 
              by = "tax_id") %>%
    mutate(group = "Gemma vs. Watts") %>%
    bind_rows(
        tab_sens %>%
            transmute(sens_pair = `Gemma - ZIRC`) %>%
            rownames_to_column("tax_id") %>%
            left_join(df_pair %>%
                          transmute(tax_id, 
                                    diff_pair = diff_DietZIRC), 
                      by = "tax_id") %>%
            mutate(group = "Gemma vs. ZIRC")
    ) %>%
    bind_rows(
        tab_sens %>%
            transmute(sens_pair = `Watts - ZIRC`) %>%
            rownames_to_column("tax_id") %>%
            left_join(df_pair %>%
                          transmute(tax_id, 
                                    diff_pair = diff_DietZIRC_DietWatts), 
                      by = "tax_id") %>%
            mutate(group = "Watts vs. ZIRC")
    )
sens_pair$diff_pair = recode(sens_pair$diff_pair * 1, 
                             `1` = "Significant",
                             `0` = "Nonsignificant")
sens_pair$group = factor(sens_pair$group, 
                         levels = c("Gemma vs. Watts",
                                    "Gemma vs. ZIRC",
                                    "Watts vs. ZIRC"))

fig_sens_pair = sens_pair %>%
    ggplot(aes(x = tax_id, y = sens_pair, color = diff_pair)) +
    geom_point() +
    scale_color_brewer(palette = "Dark2", name = NULL) +
    facet_grid(rows = vars(group), scales = "free") +
    labs(x = NULL, y = "Sensitivity Score") +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
fig_sens_pair
```



