---
title: "ANCOM-BC"
author: "Michael Sieler"
date: "2022-08-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = NA, 
                      fig.width = 6.25, fig.height = 5)



# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("ANCOMBC")


# library(ANCOMBC)
# library(tidyverse)
library(microbiome)
# library(magrittr)
# library(qwraps2)
# library(corrplot)
# library(limma)
# library(ggforce)
# library(DT)

```


## Diet and Pathogen Exposure

### Load Data

#### Single Group

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq = ps.conT1 %>% subset_samples(Diet == "ZIRC")
data = dt.conT1 %>% subset(Diet == "ZIRC")

# Relevel


# levels(data$PrePostExp) <- factor(levels(data$PrePostExp), levels = c("Unexposed", "Exposed"))
# data$PrePostExp <- relevel(factor(data$PrePostExp), ref = "Unexposed")
# 
# 
# levels(sample_data(pseq)$PrePostExp) <- factor(levels(sample_data(pseq)$PrePostExp),levels = c("Unexposed", "Exposed"))
# sample_data(pseq)$PrePostExp <- relevel(factor(sample_data(pseq)$PrePostExp), ref = "Unexposed")

# # ADD INTERACTION
# sample_data(pseq) <- microbiome::meta(pseq) %>%
#   mutate(Diet.Time = paste0(Diet,".",Body.Condition.Score), .after = Age) 
# 
# data <- data %>%
#   mutate(Diet.Time = paste0(Diet,".",Body.Condition.Score), .after = Age)
# 
# # Sanity check counts are correct
# 
# microbiome::meta(pseq) %>%
#   group_by(Diet.Time) %>%
#   count()


# Genus level data
genus_data = aggregate_taxa(pseq, "Genus")
# Family level data
family_data = aggregate_taxa(pseq, "Family")
# Phylum level data
phylum_data = aggregate_taxa(pseq, "Phylum")

# print(genus_data)
# print(family_data)
# print(phylum_data)
```

#### Multiple Groups

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq.Gemma = ps.conT0T1 %>% subset_samples(Diet == "Gemma")
data.Gemma = dt.conT0T1 %>% subset(Diet == "Gemma")

pseq.Watts = ps.conT0T1 %>% subset_samples(Diet == "Watts")
data.Watts = dt.conT0T1 %>% subset(Diet == "Watts")

pseq.ZIRC = ps.conT0T1 %>% subset_samples(Diet == "ZIRC")
data.ZIRC = dt.conT0T1 %>% subset(Diet == "ZIRC")



# Genus level data
Genus_data.Gemma = aggregate_taxa(pseq.Gemma, "Genus")
# Family level data
Family_data.Gemma = aggregate_taxa(pseq.Gemma, "Family")
# Phylum level data
Phylum_data.Gemma = aggregate_taxa(pseq.Gemma, "Phylum")

# Genus level data
Genus_data.Watts = aggregate_taxa(pseq.Watts, "Genus")
# Family level data
Family_data.Watts = aggregate_taxa(pseq.Watts, "Family")
# Phylum level data
Phylum_data.Watts = aggregate_taxa(pseq.Watts, "Phylum")

# Genus level data
Genus_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Genus")
# Family level data
Family_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Family")
# Phylum level data
Phylum_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Phylum")


```

### Single Group

```{r}

# Create Dataframes

tax.level = genus_data #phylum_data
tax.label = "Genus"
tax.data = taxa.data.table(tax.level)


out = ancombc(phyloseq = tax.level, 
              formula = "Sex", 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res = out$res
res_global = out$res_global

# Log-fold Change

tab_lfc = res$lfc
tab_se = res$se
tab_p = res$p_val
tab_diff = res$diff_abn
tab_diff

df_lfc = data.frame(res$lfc * res$diff_abn, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
df_se = data.frame(res$se * res$diff_abn, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(df_se)[-1] = paste0(colnames(df_se)[-1], ".SE")

df_lfc <- 
  df_lfc %>%
  rename(Sex = 2)

df_se <- 
  df_se %>%
  rename(Sex.SE = 2)


# Plot

df_fig = df_lfc %>% 
  dplyr::left_join(df_se, by = "Taxon_id") %>%
  # dplyr::transmute(taxon_id, bmi = bmi_groupobese, bmiSE = bmi_groupobeseSE) %>%
  filter(if_any(contains("Sex"), ~ . != 0)) %>%
  dplyr::arrange(desc(Sex)) %>%
  dplyr::mutate(direct = ifelse(Sex > 0, "Positive LFC", "Negative LFC"))
df_fig$Taxon_id = factor(df_fig$Taxon_id, levels = df_fig$Taxon_id)
df_fig$direct = factor(df_fig$direct, 
                        levels = c("Positive LFC", "Negative LFC"))
  
p = ggplot(data = df_fig, 
           aes(x = Taxon_id, y = Sex, fill = direct, color = direct)) + 
  geom_bar(stat = "identity", width = 0.7, 
           position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = Sex - Sex.SE, ymax = Sex + Sex.SE), width = 0.2,
                position = position_dodge(0.05), color = "black") + 
  labs(x = NULL, y = "Log fold change", 
       title = paste0("Waterfall Plot of ", colnames(df_lfc[2]), " (", tax.label, ")")) + 
  scale_fill_discrete(name = colnames(df_lfc[2])) +
  scale_color_discrete(name = colnames(df_lfc[2])) +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )

p

```


### Multiple Groups 


#### Load Data

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq.Gemma = ps.conT0T1 %>% subset_samples(Diet == "Gemma")
data.Gemma = dt.conT0T1 %>% subset(Diet == "Gemma")

pseq.Watts = ps.conT0T1 %>% subset_samples(Diet == "Watts")
data.Watts = dt.conT0T1 %>% subset(Diet == "Watts")

pseq.ZIRC = ps.conT0T1 %>% subset_samples(Diet == "ZIRC")
data.ZIRC = dt.conT0T1 %>% subset(Diet == "ZIRC")



# Genus level data
Genus_data.Gemma = aggregate_taxa(pseq.Gemma, "Genus")
# Family level data
Family_data.Gemma = aggregate_taxa(pseq.Gemma, "Family")
# Phylum level data
Phylum_data.Gemma = aggregate_taxa(pseq.Gemma, "Phylum")

# Genus level data
Genus_data.Watts = aggregate_taxa(pseq.Watts, "Genus")
# Family level data
Family_data.Watts = aggregate_taxa(pseq.Watts, "Family")
# Phylum level data
Phylum_data.Watts = aggregate_taxa(pseq.Watts, "Phylum")

# Genus level data
Genus_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Genus")
# Family level data
Family_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Family")
# Phylum level data
Phylum_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Phylum")

```

#### Run Ancom

```{r}
tax.label = "Genus"
tmp.formula = "PrePostExp"

tax.level.Gemma = Genus_data.Gemma 
tax.data.Gemma = taxa.data.table(tax.level.Gemma)

tax.level.Watts = Genus_data.Watts 
tax.data.Watts = taxa.data.table(tax.level.Watts)

tax.level.ZIRC = Genus_data.ZIRC 
tax.data.ZIRC = taxa.data.table(tax.level.ZIRC)

# Genus_ Phylum_ Family_

# Gemma

out.Gemma = ancombc(phyloseq = tax.level.Gemma, 
              formula = tmp.formula, 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.Gemma = out.Gemma$res
res_global.Gemma = out.Gemma$res_global


# Watts

out.Watts = ancombc(phyloseq = tax.level.Watts, 
              formula = tmp.formula, 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.Watts = out.Watts$res
res_global.Watts = out.Watts$res_global


# ZIRC

out.ZIRC = ancombc(phyloseq = tax.level.ZIRC, 
              formula = tmp.formula, 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.ZIRC = out.ZIRC$res
res_global.ZIRC = out.ZIRC$res_global



# Gemma

lfc.Gemma <- list()

lfc.Gemma$tab_lfc = res.Gemma$lfc
lfc.Gemma$tab_se = res.Gemma$se
lfc.Gemma$tab_p = res.Gemma$p_val
lfc.Gemma$tab_diff = res.Gemma$diff_abn

lfc.Gemma$df_lfc = data.frame(lfc.Gemma$tab_lfc * lfc.Gemma$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.Gemma$df_se = data.frame(lfc.Gemma$tab_se * lfc.Gemma$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.Gemma$df_se)[-1] = paste0(colnames(lfc.Gemma$df_se)[-1], "SE")

lfc.Gemma$df_lfc <- 
  lfc.Gemma$df_lfc %>%
  rename(Gemma = Body.Condition.Score)

lfc.Gemma$df_se <- 
  lfc.Gemma$df_se %>%
  rename(Gemma = Body.Condition.ScoreSE)

# Watts

lfc.Watts <- list()

lfc.Watts$tab_lfc = res.Watts$lfc
lfc.Watts$tab_se = res.Watts$se
lfc.Watts$tab_p = res.Watts$p_val
lfc.Watts$tab_diff = res.Watts$diff_abn

lfc.Watts$df_lfc = data.frame(lfc.Watts$tab_lfc * lfc.Watts$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.Watts$df_se = data.frame(lfc.Watts$tab_se * lfc.Watts$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.Watts$df_se)[-1] = paste0(colnames(lfc.Watts$df_se)[-1], "SE")

lfc.Watts$df_lfc <- 
  lfc.Watts$df_lfc %>%
  rename(Watts = Body.Condition.Score)

lfc.Watts$df_se <- 
  lfc.Watts$df_se %>%
  rename(Watts = Body.Condition.ScoreSE)

# ZIRC

lfc.ZIRC <- list()

lfc.ZIRC$tab_lfc = res.ZIRC$lfc
lfc.ZIRC$tab_se = res.ZIRC$se
lfc.ZIRC$tab_p = res.ZIRC$p_val
lfc.ZIRC$tab_diff = res.ZIRC$diff_abn

lfc.ZIRC$df_lfc = data.frame(lfc.ZIRC$tab_lfc * lfc.ZIRC$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.ZIRC$df_se = data.frame(lfc.ZIRC$tab_se * lfc.ZIRC$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.ZIRC$df_se)[-1] = paste0(colnames(lfc.ZIRC$df_se)[-1], "SE")

lfc.ZIRC$df_lfc <- 
  lfc.ZIRC$df_lfc %>%
  rename(ZIRC = Body.Condition.Score)

lfc.ZIRC$df_se <- 
  lfc.ZIRC$df_se %>%
  rename(ZIRC = Body.Condition.ScoreSE)


# Join and Pivot

## DF

df_lfc.diets <- 
lfc.Gemma$df_lfc %>%
  left_join(lfc.Watts$df_lfc, by = "Taxon_id",  na_matches = "never") %>% 
  left_join(lfc.ZIRC$df_lfc, by = "Taxon_id",  na_matches = "never") %>% 
  replace(is.na(.), 0) %>%
  pivot_longer(cols = 2:4, names_to = "Diet")

## SE

df_se.diets <- 
lfc.Gemma$df_se %>%
  left_join(lfc.Watts$df_se, by = "Taxon_id",  na_matches = "never") %>% 
  left_join(lfc.ZIRC$df_se, by = "Taxon_id",  na_matches = "never") %>% 
  replace(is.na(.), 0) %>%
  pivot_longer(cols = 2:4, names_to = "Diet")


# df_lfc.diets
# df_se.diets



# Plot

df_fig_diets = df_lfc.diets %>% 
  dplyr::left_join(df_se.diets, by = c("Taxon_id", "Diet"), suffix = c("", ".SE")) %>%
  filter(if_any(contains("value"), ~ . != 0)) %>%
  dplyr::arrange(desc(value)) %>%
  dplyr::mutate(direct = ifelse(value > 0, "Positive LFC", "Negative LFC"))
# df_fig_diets$Taxon_id = df_fig_diets %>%
#   group_by(Taxon_id, Diet) %>% 
#   factor(levels = df_fig_diets$Taxon_id)
df_fig_diets$direct = factor(df_fig_diets$direct, 
                        levels = c("Positive LFC", "Negative LFC"))
  
p_diets =
ggplot(data = df_fig_diets, 
           aes(x = reorder(Taxon_id, -value, FUN = mean), y = value, fill = Diet, color = Diet), group = Diet) + 
  geom_bar(stat = "identity", 
           position = position_dodge2(width = 1, preserve = "single"), width = .4) +
  geom_errorbar(aes(ymin = value - value.SE, ymax = value + value.SE), width = 0.4,
                position = position_dodge2(width = 1, preserve = "single"), color = "black") +
  labs(x = NULL, y = "Log fold change",
       title = paste0("Waterfall Plot of ", tmp.formula, " (", tax.label, ")")) +
  scale_fill_manual(values = pal.Dark2) +
  scale_color_manual(values = pal.Dark2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )

p_diets

```