---
title: "ANCOM-BC"
author: "Michael Sieler"
date: "2022-08-15"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, comment = NA, 
                      fig.width = 6.25, fig.height = 5)



# if (!requireNamespace("BiocManager", quietly=TRUE))
#     install.packages("BiocManager")
# BiocManager::install("ANCOMBC")


# library(ANCOMBC)
# library(tidyverse)
library(microbiome)
# library(magrittr)
# library(qwraps2)
# library(corrplot)
# library(limma)
# library(ggforce)
# library(DT)

```


## Diet and Pathogen Exposure

### Load Data

#### Single Group

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq = ps.conT0T1 %>% subset_samples(Diet == "Gemma")
data = dt.conT0T1 %>% subset(Diet == "Gemma")

# Relevel


# levels(data$PrePostExp) <- factor(levels(data$PrePostExp), levels = c("Unexposed", "Exposed"))
# data$PrePostExp <- relevel(factor(data$PrePostExp), ref = "Unexposed")
# 
# 
# levels(sample_data(pseq)$PrePostExp) <- factor(levels(sample_data(pseq)$PrePostExp),levels = c("Unexposed", "Exposed"))
# sample_data(pseq)$PrePostExp <- relevel(factor(sample_data(pseq)$PrePostExp), ref = "Unexposed")

# ADD INTERACTION
sample_data(pseq) <- microbiome::meta(pseq) %>%
  mutate(Diet.Time = paste0(Diet,".",Timepoint), .after = Age) 

data <- data %>%
  mutate(Diet.Time = paste0(Diet,".",Timepoint), .after = Age)

# Sanity check counts are correct

microbiome::meta(pseq) %>%
  group_by(Diet.Time) %>%
  count()


# Genus level data
genus_data = aggregate_taxa(pseq, "Genus")
# Family level data
family_data = aggregate_taxa(pseq, "Family")
# Phylum level data
phylum_data = aggregate_taxa(pseq, "Phylum")

# print(genus_data)
# print(family_data)
# print(phylum_data)
```

#### Multiple Groups

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq.Gemma = ps.conT0T1 %>% subset_samples(Diet == "Gemma")
data.Gemma = dt.conT0T1 %>% subset(Diet == "Gemma")

pseq.Watts = ps.conT0T1 %>% subset_samples(Diet == "Watts")
data.Watts = dt.conT0T1 %>% subset(Diet == "Watts")

pseq.ZIRC = ps.conT0T1 %>% subset_samples(Diet == "ZIRC")
data.ZIRC = dt.conT0T1 %>% subset(Diet == "ZIRC")



# Genus level data
Genus_data.Gemma = aggregate_taxa(pseq.Gemma, "Genus")
# Family level data
Family_data.Gemma = aggregate_taxa(pseq.Gemma, "Family")
# Phylum level data
Phylum_data.Gemma = aggregate_taxa(pseq.Gemma, "Phylum")

# Genus level data
Genus_data.Watts = aggregate_taxa(pseq.Watts, "Genus")
# Family level data
Family_data.Watts = aggregate_taxa(pseq.Watts, "Family")
# Phylum level data
Phylum_data.Watts = aggregate_taxa(pseq.Watts, "Phylum")

# Genus level data
Genus_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Genus")
# Family level data
Family_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Family")
# Phylum level data
Phylum_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Phylum")


```

### Run AncomBC

#### Single Group

```{r}

# Create Dataframes

tax.level = genus_data #phylum_data
tax.label = "Genus"
tax.data = taxa.data.table(tax.level)


out = ancombc(phyloseq = tax.level, 
              formula = "Timepoint", 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res = out$res
res_global = out$res_global


```

#### Multiple Groups


## Global

### Data wrangling

```{r}

# Global

tab_w = res_global[, "W", drop = FALSE]
tab_p = res_global[, "p_val", drop = FALSE]
tab_q = res_global[, "q_val", drop = FALSE]
tab_diff = res_global[, "diff_abn", drop = FALSE]

# Log transform

samp_frac = out$samp_frac
# Replace NA with 0
samp_frac[is.na(samp_frac)] = 0 

# Add pesudo-count (1) to avoid taking the log of 0
log_obs_abn = log(abundances(tax.level) + 1) 

# Adjust the log observed abundances
log_obs_abn_adj = t(t(log_obs_abn) - samp_frac)

# Prep for visualization

sig_taxa = res_global %>%
  tibble::rownames_to_column("Taxon") %>%
  dplyr::filter(diff_abn == TRUE) %>%
  .$Taxon

df_sig = as.data.frame(t(log_obs_abn_adj[sig_taxa, ])) %>%
  tibble::rownames_to_column("Sample") %>%
  dplyr::left_join(data %>%
                     dplyr::select(Sample, Diet, PrePostExp, Diet.Exp),
                   by = "Sample") %>%
  dplyr::filter(!is.na(Diet)) %>%
  tidyr::pivot_longer(cols = -one_of("Sample", "Diet", "PrePostExp", "Diet.Exp"), 
                      names_to = "Taxon", values_to = "value")

df_plot = df_sig %>%
  dplyr::group_by(Diet.Exp, Diet, PrePostExp, Taxon) %>%
  dplyr::summarise_if(is.numeric, mean, na.rm = TRUE) %>%
  dplyr::filter(!str_detect(Taxon, "^Bacteria")) %>% # Filter out unclassified taxa
  dplyr::mutate(value = round(value, 2)) %>%
  dplyr::arrange(Diet)
df_plot$Taxon = factor(df_plot$Taxon, levels = sig_taxa)

# Join higher taxanomic levels
df_plot = df_plot %>%
  rename_with(~tax.label, Taxon) %>%
  left_join(., tax.data %>% dplyr::select(-last_col()), by = tax.label)

lo = floor(min(df_plot$value))
up = ceiling(max(df_plot$value))
mid = (lo + up)/2

```

### Visualization

```{r}
p_heat_diet = df_plot %>%
  ggplot(aes(x = Diet, y = Taxon, fill = value)) + 
  geom_tile(color = "white") +
  facet_grid(as.formula(paste0(ifelse(tax.label == "Phylum", ".", "Phylum"), "~ PrePostExp")), scales = "free", space = "free", switch = "both") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       na.value = "white", midpoint = mid, limit = c(lo, up),
                       name = NULL) +
  geom_text(aes(Diet, Taxon, label = value), color = "black", size = 4) +
  labs(x = NULL, y = NULL, title = paste0("Heat map of bias-corrected log observed abundances (", tax.label ,")")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        strip.text.y.left = element_text(angle = 0)
        )

p_heat_diet
```


```{r}

p_heat_exp = df_plot %>%
  ggplot(aes(x = PrePostExp, y = Taxon, fill = value)) + 
  geom_tile(color = "white") +
  facet_grid(as.formula(paste0(ifelse(tax.label == "Phylum", ".", "Phylum"), "~ Diet")), scales = "free", space = "free", switch = "both") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       na.value = "white", midpoint = mid, limit = c(lo, up),
                       name = NULL) +
  geom_text(aes(PrePostExp, Taxon, label = value), color = "black", size = 4) +
  labs(x = NULL, y = NULL, title = paste0("Heat map of bias-corrected log observed abundances (", tax.label ,")")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        strip.text.y.left = element_text(angle = 0)
        )
p_heat_exp

```

```{r}

p_heat_Diet.Exp = df_plot %>%
  ggplot(aes(x = Diet.Exp, y = Taxon, fill = value)) + 
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
                       na.value = "white", midpoint = mid, limit = c(lo, up),
                       name = NULL) +
  geom_text(aes(Diet.Exp, Taxon, label = value), color = "black", size = 4) +
  labs(x = NULL, y = NULL, title = paste0("Heat map of bias-corrected log observed abundances (", tax.label ,")")) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
p_heat_Diet.Exp

```

```{r}
# test <- df_plot %>%
#   as.data.frame %>%
#   dplyr::select(Taxon, Diet, PrePostExp, value) %>% arrange(Taxon) %>%
#   pivot_wider(names_from = PrePostExp, values_from = "value") %>% arrange(Taxon) %>%
#   mutate(max.value = pmax(`Pre-exposure`, Exposed, Unexposed), # https://stackoverflow.com/a/32978686
#          min.value = pmin(`Pre-exposure`, Exposed, Unexposed)) %>%
#   mutate(direction = case_when(`Pre-exposure` == max.value ~ "negative",
#                                `Pre-exposure` == min.value ~ "positive",
#                                `Pre-exposure` != min.value & `Pre-exposure` != max.value ~ "neutral")) %>%
#   mutate(direction = fct_relevel(direction, c("positive", "neutral", "negative")))
```

#### Lollipop

```{r}
  
diffAbund_DietExp <-
df_plot %>%
  as.data.frame %>%
  dplyr::select(-1) %>%
  pivot_wider(names_from = PrePostExp, values_from = "value") %>% arrange(Taxon) %>%
  mutate(max.value = pmax(`Pre-exposure`, Exposed, Unexposed), # https://stackoverflow.com/a/32978686
         min.value = pmin(`Pre-exposure`, Exposed, Unexposed)) %>%
  mutate(direction = case_when(`Pre-exposure` == max.value ~ "negative",
                               `Pre-exposure` == min.value ~ "positive",
                               `Pre-exposure` != min.value & `Pre-exposure` != max.value ~ "neutral")) %>%
  mutate(mid.value = mean(max.value + min.value)) %>%
  mutate(direction = fct_relevel(direction, c("positive", "neutral", "negative"))) %>%
  
  ggplot(aes(group = Diet)) +
  
  geom_point(data = df_plot, aes(y = Taxon, x = value, fill = PrePostExp), color = "Black", shape = 21, alpha=0, inherit.aes = F, guide = F) + # This disgusting line of code allows me to sneak in "PrePostExp" variables to the legend
  
  geom_segment(aes(y=Taxon, yend=Taxon, x=`min.value`, xend=`max.value`, linetype = direction), position = position_nudge(y = c(-0.25, 0, .25))) +
  
  geom_point( aes(y=Taxon, x=`Pre-exposure`, color = Diet), fill = col.prepostexp[1], shape = 21, stroke = 1.5, size = 3, position = position_dodge(width=.75)) +
  geom_point( aes(y=Taxon, x=`Exposed`, color = Diet), fill = col.prepostexp[2], shape = 21, stroke = 1.5, size = 3, position = position_dodge(width=.75) ) +
  geom_point( aes(y=Taxon, x=`Unexposed`, color = Diet), fill = col.prepostexp[3], shape = 21, stroke = 1.5, size = 3, position = position_dodge(width=.75) ) +

  facet_grid(as.formula(paste0(ifelse(tax.label == "Phylum", ".", "Phylum"), "~ .")), scales = "free", space = "free", switch="both") +
  
  scale_color_manual(values = c(col.diet, col.prepostexp), breaks = c("Gemma", "Watts", "ZIRC"), name = "Diet") +
  scale_fill_manual(values = c(col.prepostexp), breaks = c("Pre-exposure", "Exposed", "Unexposed"), name = "Exposure") +
  scale_linetype_manual(values = c("dotted", "solid", "dashed"), name = "Ref to Pre-Exp") +
  labs(title = paste0("Heat map of bias-corrected log observed abundances (", tax.label ,")"),
       x = "Abundance (log transformed)",
       y = "Phyla",
       caption = str_wrap("Results from the ANCOM-BC global test showing taxa that are signficantly differentially abundant between at least two groups across diets (Gemma, Watts, and ZIRC) and exposures (Pre-exposure, Exposed, and Unexposed). P.adj = BH."), 80) +
  guides(color = guide_legend(title="Diet",
                              override.aes = list(fill = c(col.diet[1],col.diet[2],col.diet[3]))
                              ),
         fill = guide_legend(title="Exposure",
                              override.aes = list(color = c(col.prepostexp[1], col.prepostexp[2], col.prepostexp[3]), 
                                                  fill = c(col.prepostexp[1], col.prepostexp[2], col.prepostexp[3]), 
                                                  alpha = 1, size = 4)
                              ),
         size = F,
         alpha = F)  +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5),
        plot.caption = element_text(hjust = 0),
        strip.text.y.left = element_text(angle = 0)
        )
  

diffAbund_DietExp

```

```{r}
df_heat %>%
  as.data.frame %>%
  dplyr::select(Taxon, Diet, PrePostExp, value) %>%
  pivot_wider(names_from = PrePostExp, values_from = "value") %>% arrange(Taxon) 
```



## Comparative

### Single Group

```{r}
# Log-fold Change

tab_lfc = res$lfc
tab_se = res$se
tab_p = res$p_val
tab_diff = res$diff_abn
tab_diff
```





### Visualization

#### Single Group

```{r}
df_lfc = data.frame(res$lfc * res$diff_abn, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
df_se = data.frame(res$se * res$diff_abn, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(df_se)[-1] = paste0(colnames(df_se)[-1], "SE")


# Plot

df_fig_timepoint = df_lfc %>% 
  dplyr::left_join(df_se, by = "Taxon_id") %>%
  # dplyr::transmute(taxon_id, bmi = bmi_groupobese, bmiSE = bmi_groupobeseSE) %>%
  filter(if_any(contains("Timepoint"), ~ . != 0)) %>%
  dplyr::arrange(desc(Timepoint6mpf)) %>%
  dplyr::mutate(direct = ifelse(Timepoint6mpf > 0, "Positive LFC", "Negative LFC"))
df_fig_timepoint$Taxon_id = factor(df_fig_timepoint$Taxon_id, levels = df_fig_timepoint$Taxon_id)
df_fig_timepoint$direct = factor(df_fig_timepoint$direct, 
                        levels = c("Positive LFC", "Negative LFC"))
  
p_time = ggplot(data = df_fig_timepoint, 
           aes(x = Taxon_id, y = Timepoint6mpf, fill = direct, color = direct)) + 
  geom_bar(stat = "identity", width = 0.7, 
           position = position_dodge(width = 0.4)) +
  geom_errorbar(aes(ymin = Timepoint6mpf - Timepoint6mpfSE, ymax = Timepoint6mpf + Timepoint6mpfSE), width = 0.2,
                position = position_dodge(0.05), color = "black") + 
  labs(x = NULL, y = "Log fold change", 
       title = paste0("Waterfall Plot of ", colnames(df_lfc[2]), " (", tax.label, ")")) + 
  scale_fill_discrete(name = colnames(df_lfc[2])) +
  scale_color_discrete(name = colnames(df_lfc[2])) +
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )

p_time

```

### Multiple Groups 


#### Load Data

```{r data1}
# data(atlas1006) 
# Subset to baseline
pseq.Gemma = ps.conT0T1 %>% subset_samples(Diet == "Gemma")
data.Gemma = dt.conT0T1 %>% subset(Diet == "Gemma")

pseq.Watts = ps.conT0T1 %>% subset_samples(Diet == "Watts")
data.Watts = dt.conT0T1 %>% subset(Diet == "Watts")

pseq.ZIRC = ps.conT0T1 %>% subset_samples(Diet == "ZIRC")
data.ZIRC = dt.conT0T1 %>% subset(Diet == "ZIRC")



# Genus level data
Genus_data.Gemma = aggregate_taxa(pseq.Gemma, "Genus")
# Family level data
Family_data.Gemma = aggregate_taxa(pseq.Gemma, "Family")
# Phylum level data
Phylum_data.Gemma = aggregate_taxa(pseq.Gemma, "Phylum")

# Genus level data
Genus_data.Watts = aggregate_taxa(pseq.Watts, "Genus")
# Family level data
Family_data.Watts = aggregate_taxa(pseq.Watts, "Family")
# Phylum level data
Phylum_data.Watts = aggregate_taxa(pseq.Watts, "Phylum")

# Genus level data
Genus_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Genus")
# Family level data
Family_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Family")
# Phylum level data
Phylum_data.ZIRC = aggregate_taxa(pseq.ZIRC, "Phylum")

```

#### Run Ancom

```{r}
tax.label = "Genus"

tax.level.Gemma = Genus_data.Gemma 
tax.data.Gemma = taxa.data.table(tax.level.Gemma)

tax.level.Watts = Genus_data.Watts 
tax.data.Watts = taxa.data.table(tax.level.Watts)

tax.level.ZIRC = Genus_data.ZIRC 
tax.data.ZIRC = taxa.data.table(tax.level.ZIRC)

# Genus_ Phylum_ Family_

# Gemma

out.Gemma = ancombc(phyloseq = tax.level.Gemma, 
              formula = "Timepoint", 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.Gemma = out.Gemma$res
res_global.Gemma = out.Gemma$res_global


# Watts

out.Watts = ancombc(phyloseq = tax.level.Watts, 
              formula = "Timepoint", 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.Watts = out.Watts$res
res_global.Watts = out.Watts$res_global


# ZIRC

out.ZIRC = ancombc(phyloseq = tax.level.ZIRC, 
              formula = "Timepoint", 
              p_adj_method = "BH", 
              # lib_cut = 0, 
              # prv_cut = 0,
              # group = "Diet", # Set variable if "struct_zero = T". (e.g. you had two groups treated or not with antibiotics. "Antibiotics")
              # struc_zero = F,  # Set true if you expect certain treatments to select against certain taxa (e.g. antibiotics, germ-free)
              neg_lb = ifelse(tax.label == "Genus", F, T),  # F is more conservative, Set to F with ASV/Genus level, Set T with higher tax (e.g. Family, Phylum)
              tol = 1e-05, 
              max_iter = 100,
              conserve = T, 
              alpha = 0.05, 
              # global = T
              #assay_name = "counts"
              )

res.ZIRC = out.ZIRC$res
res_global.ZIRC = out.ZIRC$res_global



# Gemma

lfc.Gemma <- list()

lfc.Gemma$tab_lfc = res.Gemma$lfc
lfc.Gemma$tab_se = res.Gemma$se
lfc.Gemma$tab_p = res.Gemma$p_val
lfc.Gemma$tab_diff = res.Gemma$diff_abn

lfc.Gemma$df_lfc = data.frame(lfc.Gemma$tab_lfc * lfc.Gemma$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.Gemma$df_se = data.frame(lfc.Gemma$tab_se * lfc.Gemma$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.Gemma$df_se)[-1] = paste0(colnames(lfc.Gemma$df_se)[-1], "SE")

lfc.Gemma$df_lfc <- 
  lfc.Gemma$df_lfc %>%
  rename(Gemma.6mpf = Timepoint6mpf)

lfc.Gemma$df_se <- 
  lfc.Gemma$df_se %>%
  rename(Gemma.6mpf = Timepoint6mpfSE)

# Watts

lfc.Watts <- list()

lfc.Watts$tab_lfc = res.Watts$lfc
lfc.Watts$tab_se = res.Watts$se
lfc.Watts$tab_p = res.Watts$p_val
lfc.Watts$tab_diff = res.Watts$diff_abn

lfc.Watts$df_lfc = data.frame(lfc.Watts$tab_lfc * lfc.Watts$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.Watts$df_se = data.frame(lfc.Watts$tab_se * lfc.Watts$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.Watts$df_se)[-1] = paste0(colnames(lfc.Watts$df_se)[-1], "SE")

lfc.Watts$df_lfc <- 
  lfc.Watts$df_lfc %>%
  rename(Watts.6mpf = Timepoint6mpf)

lfc.Watts$df_se <- 
  lfc.Watts$df_se %>%
  rename(Watts.6mpf = Timepoint6mpfSE)

# ZIRC

lfc.ZIRC <- list()

lfc.ZIRC$tab_lfc = res.ZIRC$lfc
lfc.ZIRC$tab_se = res.ZIRC$se
lfc.ZIRC$tab_p = res.ZIRC$p_val
lfc.ZIRC$tab_diff = res.ZIRC$diff_abn

lfc.ZIRC$df_lfc = data.frame(lfc.ZIRC$tab_lfc * lfc.ZIRC$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
lfc.ZIRC$df_se = data.frame(lfc.ZIRC$tab_se * lfc.ZIRC$tab_diff, check.names = FALSE) %>% 
  rownames_to_column("Taxon_id")
colnames(lfc.ZIRC$df_se)[-1] = paste0(colnames(lfc.ZIRC$df_se)[-1], "SE")

lfc.ZIRC$df_lfc <- 
  lfc.ZIRC$df_lfc %>%
  rename(ZIRC.6mpf = Timepoint6mpf)

lfc.ZIRC$df_se <- 
  lfc.ZIRC$df_se %>%
  rename(ZIRC.6mpf = Timepoint6mpfSE)


# Join and Pivot

## DF

df_lfc.diets <- 
lfc.Gemma$df_lfc %>%
  left_join(lfc.Watts$df_lfc, by = "Taxon_id",  na_matches = "never") %>% 
  left_join(lfc.ZIRC$df_lfc, by = "Taxon_id",  na_matches = "never") %>% 
  replace(is.na(.), 0) %>%
  pivot_longer(cols = 2:4, names_to = "Diet")

## SE

df_se.diets <- 
lfc.Gemma$df_se %>%
  left_join(lfc.Watts$df_se, by = "Taxon_id",  na_matches = "never") %>% 
  left_join(lfc.ZIRC$df_se, by = "Taxon_id",  na_matches = "never") %>% 
  replace(is.na(.), 0) %>%
  pivot_longer(cols = 2:4, names_to = "Diet")


# df_lfc.diets
# df_se.diets



# Plot

df_fig_diets = df_lfc.diets %>% 
  dplyr::left_join(df_se.diets, by = c("Taxon_id", "Diet"), suffix = c("", ".SE")) %>%
  filter(if_any(contains("value"), ~ . != 0)) %>%
  dplyr::arrange(desc(value)) %>%
  dplyr::mutate(direct = ifelse(value > 0, "Positive LFC", "Negative LFC"))
# df_fig_diets$Taxon_id = df_fig_diets %>%
#   group_by(Taxon_id, Diet) %>% 
#   factor(levels = df_fig_diets$Taxon_id)
df_fig_diets$direct = factor(df_fig_diets$direct, 
                        levels = c("Positive LFC", "Negative LFC"))
  
p_diets =
ggplot(data = df_fig_diets, 
           aes(x = reorder(Taxon_id, -value, FUN = mean), y = value, fill = Diet, color = Diet), group = Diet) + 
  geom_bar(stat = "identity", 
           position = position_dodge2(width = 1, preserve = "single"), width = .4) +
  geom_errorbar(aes(ymin = value - value.SE, ymax = value + value.SE), width = 0.4,
                position = position_dodge2(width = 1, preserve = "single"), color = "black") +
  labs(x = NULL, y = "Log fold change",
       title = paste0("Waterfall Plot of ", colnames(df_lfc[2]), " (", tax.label, ")")) +
  scale_fill_manual(values = pal.Dark2) +
  scale_color_manual(values = pal.Dark2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5),
        panel.grid.minor.y = element_blank(),
        axis.text.x = element_text(angle = 60, hjust = 1)
        )

p_diets

```